### PR TITLE
Full upgrade

### PR DESCRIPTION
**Pull request by yalh76**
* Apply example_ynh
* upgrade to 2021-02-18

### CODE REVIEW

**Comment by yalh76** [comment]
!testme

**Comment by yalh76** [comment]
# Own CI result for Revision: 7658edc344577448a136e9f5799dc14b76276e7c 

image

**Comment by yalh76** [comment]
!testme

**Review by alexAubin — APPROVED** [review]

**Review by kay0u — APPROVED** [review]
:+1:

**Pull request merged**
